version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "last3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1imm0k84hljnc"
s3_prefix = "last3"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SubcribeTable=\"my_connectionsIds\" SubcribTopic=\"my_Topics\""

